<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse"
       data-target="#example-navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="menu.aspx">Inicio</a>
  </div>
  <div class="collapse navbar-collapse" id="example-navbar-collapse">
    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Mantenimiento <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li>
            <a href="colaborador.aspx">Colaborador</a>
          </li>
          <!--<li>
            <a href="#">EJB</a>
          </li>
          <li>
            <a href="#">Jasper Report</a>
          </li>
          <li class="divider"></li>
          <li>
            <a href="#">Separated link</a>
          </li>
          <li class="divider"></li>
          <li>
            <a href="#">One more separated link</a>
          </li>-->
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Visita <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li>
            <a href="visitacliente.aspx">Asignar Visita Tecnico</a>
          </li>
          <!--<li>
            <a href="#">EJB</a>
          </li>
          <li>
            <a href="#">Jasper Report</a>
          </li>
          <li class="divider"></li>
          <li>
            <a href="#">Separated link</a>
          </li>
          <li class="divider"></li>
          <li>
            <a href="#">One more separated link</a>
          </li>-->
        </ul>
      </li>
      <!--<li>
        <a href="#">SVN</a>
      </li>-->
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Sesion <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li>
            <a href="CerrarSession.aspx">Cerrar</a>
          </li>
          <!--<li>
            <a href="#">EJB</a>
          </li>
          <li>
            <a href="#">Jasper Report</a>
          </li>
          <li class="divider"></li>
          <li>
            <a href="#">Separated link</a>
          </li>
          <li class="divider"></li>
          <li>
            <a href="#">One more separated link</a>
          </li>-->
        </ul>
      </li>
    </ul>
  </div>
</nav>
